### ISSUE TITLE
Saas Middleware Backend Exception Handling

### ISSUE THREAD

**Issue by HeikoAydt** [cooling-singapore/saas-middleware#116]
**Description**
We need to discuss how to do exception handling in the SaaS Middleware backend code. In particular, we should discuss if and what kind of exceptions to define and use (as opposed to just using `Exception` which is too generic). We should also decide whether to write this down as a guidelines document or a more formal SRS document.

**Outcomes**
- [x] Issue to create either a Guideline *OR* SRS document that describes/specifies how exceptions are handled in the SaaS Middleware backend and what different exception types mean, when they should be used and how they should be handled: #145
- [x] Define exception class hierarchy. Also define base class with useful messages that provides methods to obtain status codes, reasons (human-readable) and possibly a reference for how to lookup the relevant stack trace in the logs.
- [x] Update `saas.cryptography`: #161 
- [x] Update `saas.dor`: #157
- [x] Update `saas.email`: #162
- [x] Update `saas.keystore`: #161
- [x] Update `saas.nodedb`: #147
- [x] Update `saas.p2p`: #74
- [x] Update `saas.rest`: #150
- [x] Update `saas.rti`: #152
- [x] Update `saas`:
- [x] Update `cli`: #170

**Related**
#131
#2
