### ISSUE TITLE
Refactor/Redesign NodeDB Subsystem

### ISSUE THREAD

**Issue by HeikoAydt** [cooling-singapore/saas-middleware#147]
**Description**
The `NodeDB` subsystem needs to be overhauled in terms of housekeeping and specific issues with this the subsystem.

**Deliverables (Housekeeping)**
- [x] Ensure data type hints are used everywhere
- [x] Move schemas (if any)
- [x] Implement exceptions according to guidelines
- [x] Implement logging according to guidelines

**Deliverables (Module-specific)**
- [x] Address issue with encapsulation: #72
- [x] Address issue/bug with inconsistency: #118
