### ISSUE TITLE
Refactor/Redesign RTI Subsystem

### ISSUE THREAD

**Issue by HeikoAydt** [cooling-singapore/saas-middleware#152]
**Description**
The `RTI` subsystem needs to be overhauled in terms of housekeeping and specific issues with this the subsystem.

**Deliverables (Housekeeping)**
- [x] Ensure data type hints are used everywhere
- [x] Move schemas (if any)
- [x] Implement exceptions according to guidelines
- [x] Implement logging according to guidelines

**Deliverables (Module-specific)**
- [x] Fix issue when fetching data objects with the same object id: #110
- [x] Add JSON schema support for JSONObject data type input: #121
- [x] Add support for different SSH profiles by the same RTI: #128
- [x] Handle case of unknown SSH host: #136
- [x] Add support logging progress information during job execution: #144
- [x] Add support for pushing data objects during job execution: #142
