### ISSUE TITLE
Refactor/Redesign DOR Subsystem

### ISSUE THREAD

**Issue by HeikoAydt** [cooling-singapore/saas-middleware#157]
**Description**
The `DOR` subsystem needs to be overhauled in terms of housekeeping and specific issues with this the subsystem.

**Deliverables (Housekeeping)**
- [x] Ensure data type hints are used everywhere
- [x] Move schemas (if any)
- [x] Implement exceptions according to guidelines
- [x] Implement logging according to guidelines

**Deliverables (Module-specific)**
- [x] Consolidate storage of meta information for data objects: #156
- [x] Strictly separate immutable data object properties from tags but make both searchable: #158
- [x] Modify DOR implementation according to outcomes of discussion: #159
