### ISSUE TITLE
Handling of data object meta information

### ISSUE THREAD

**Issue by HeikoAydt** [cooling-singapore/saas-middleware#159]
**Description**
When a data object is added to a DOR, a meta information record is created. This record is currently not synced with other nodes. The same applies for tags and permission information. Only the DOR that is the custodian for the data object keeps this information. When a data object is removed, the meta information is deleted as well. There are also other matters concerning the meta information contents that should be discussed.

**Outcomes**
The following topics should be discussed and decided:
- [x] Should meta information be synced with other nodes? This would ensure that meta information (including recipes) isn't lost if a node goes offline or is deleted.
- [x] Should meta information be deleted? If yes, then this seems to go against the principle of reproducibility. If no, then there will eventually be (potentially) a lot of garbage in the database. The latter could be resolved by some garbage collection method which could be run manually if and when needed.
- [x] If meta information is kept, what happens when the same data object is recreated or added again to the DOR?
- [x] How to handle the case of different recipes resulting in the same data object? One option could be to simply allow multiple recipes.
- [x] Meta information hash should probably not include things like `created_by` and `created_t` because that would mean the same data object created at a different time would result in a different object id which doesn't make sense.
- [x] Is the meta information hash really needed or is the content hash sufficient?
