### ISSUE TITLE
Redesign/Refactor CLI Subsystem

### ISSUE THREAD

**Issue by HeikoAydt** [cooling-singapore/saas-middleware#170]
**Description**
The `CLI` subsystem needs to be overhauled in terms of housekeeping and specific issues with this the subsystem.

**Deliverables (Housekeeping)**
- [x] Ensure data type hints are used everywhere
- [x] Move schemas (if any)
- [x] Implement exceptions according to guidelines
- [x] Implement logging according to guidelines

**Deliverables (Module-specific)**
- [x] Improve how CLI handles cases of unknown/unpublished identities: #139
- [x] Support multi-selection for RTI processor undeployment: #129
- [x] Remove redundant processor lookup when deploying processor: #135
