### ISSUE TITLE
First public release

### ISSUE THREAD

**Issue by HeikoAydt** [cooling-singapore/saas-middleware#194]
**Description**
Remains to be done:
- [ ] Discuss/sort out license (preference: MIT) with Ander/Kristina #198
- [x] Setup Open API server (ideally using Github) #195
- [x] Create public `saas-middleware-sdk` and migrate relevant modules code/docs.
- [ ] Delete obsolete `saas-middleware-x` repos
- [ ] Update source code documentation in `saas-middleware-sdk`.
- [x] Update README.md for `saas-middleware` #206 
- [ ] Update README.md for `saas-processor-sdk` #208
- [x] Update OpenAPI spec/documentation #95
- [ ] Improve robustness of CLI
- [x] Deploy SaaS Middleware on Beta testnet
- [ ] Sort out Github release (incl. tagging)

**Outcomes**
- [ ] Entire SaaS Middleware repo ready for first public release
