### ISSUE TITLE
Enhance Staging and Production Environment Deployments

### ISSUE THREAD

**Issue by BrianLYS** [cooling-singapore/saas-middleware#407]
**Description**
Currently manual steps are being done to deploy to staging and production.
We require automation of set up to staging and production environments.

**Deliverables**
- [x] Dockerise DUCT Frontend
- [x] Dockerise individual Backend services from `duct-servers` repository 

- [x] Open a pull request on `digital-urban-climate-twin` repo
- [x] Open a pull request on `duct-servers` repo

**Low Priority**
- [ ] Optimise DUCT Frontend
