### ISSUE TITLE
Security Redesign of SaaS Middleware

### ISSUE THREAD

**Issue by HeikoAydt** [cooling-singapore/saas-middleware#46]
**Description**
The data security concept for the SaaS Middleware is only loosely defined at the moment. In order for the SaaS Middlware to achieve higher TRL levels and ultimately become production ready, there needs to be a solid concept of data is secured by the middleware.

**Outcomes**
- [x] Extend and refactor cryptography primitive wrappers: #48
- [x] Develop keystore feature: #56
- [x] Refactor node class: #58
- [x] Develop distributed identity lookup table: #60
- [x] Implement security concept: #45
