### ISSUE TITLE
Create remote processor deployment tool

### ISSUE THREAD

**Issue by reyery** [cooling-singapore/saas-middleware#53]
**Description**
Currently, the SaaS RTI is only able to deploy processors that are found and uploaded to the DOR (i.e. user has to 'build'/upload the whole processor 'package' manually to the SaaS DOR before the RTI and deploy it). We should also allow the user to be able to point the RTI to a url e.g. a remote git location such as GItHub containing the processor code, list of python dependencies, where the package will be built automatically 

**Outcomes**
- [x] Decide on an appropriate template/structure for the remote git location
- [x] Create template as a GitHub template
- [x] Create tool
- [ ] Test tool with a dummy/representative processor (e.g. WRF) based on template
